[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn -w 2 -b 0.0.0.0:$PORT app:app --timeout 120"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

